### ISSUE TITLE
Hide search highlights on `:noh`

### ISSUE THREAD

**Issue by PowerUser64** [lewis6991/satellite.nvim#11]
**Description**
After I'm done searching for something, I always use `:noh` to disable the search result highlighting, but satellite doesn't respond to it.

**The solution I'd like**
When the `:noh` command is issued, satellite should hide the markers showing where search results are.

**Alternatives**
Currently, you can force the markers to go away by doing a blank search (press `/` then enter), which may technically be abusing a bug, because the blank search does not make the highlights go away in the editor.

Thank you for all the great plugins!

**Comment by rudotriton** [comment]
there is `:SatelliteRefresh`, if you have `:noh` behind a mapping, similar to the default `ctrl-l` one, then `<Cmd>noh | SatelliteRefresh<CR>` may work, typing this out each time is certainly not ideal. a shorter user command could do

there is an event, `OptionSet`, but i'm not sure that `noh` triggers it

**Comment by PowerUser64** [comment]
Ooh! Good to know. That should do exactly what I want.
I've added this to my configuration:
```lua
if packer_plugins.satellite.nvim ~= nil then  -- only do this if satellite is loaded
   vim.cmd 'nnoremap <M-h> <cmd>noh | SatelliteRefresh<CR>'
   vim.cmd 'inoremap <M-h> <cmd>noh | SatelliteRefresh<CR>'
end
```
\-\-
Closing issue because it's easy to work around, but this could still be something worth looking into if anyone considers it a bug.

**Comment by gegoune** [comment]
Please note that there is default `<C-l>` mapping that does `<Cmd>nohlsearch|diffupdate|normal! <C-L><CR>`. You can override it with added `SatelliteRefresh`.

@lewis6991 Is it README worthy?

**Comment by PowerUser64** [comment]
I just noticed I overrode that bind to use for switching windows faster, glad I know what it does now.

**Comment by lewis6991** [comment]
Note that Satellite already refreshes the bars when `:noh` is ran interactively: https://github.com/lewis6991/satellite.nvim/blob/f9d0b08faebe97ccd3822df5d1581b0757c0ca66/lua/satellite/handlers/search.lua#L127-L130

However, this doesn't work when ex commands are run in plugins or mappings. I have no idea if it's even possible to hook into these events.
