### ISSUE TITLE
Unable to setup plugin

### ISSUE THREAD

**Issue by kaname-png** [lewis6991/satellite.nvim#19]
**Describe the bug**
When I try to configure the plugin I get an error about the plugin code.

**To Reproduce**
1. install plugin
2. Try to setup
3. See error

**Expected behavior**
To be able to use the plugin.

**Error**
E5113: Error while calling lua chunk: ...\pack\packer\start\satellite.nvim/lua/satellite/view.lua:178: unknown option 'winbar'

**Additional context**
I have neovim 0.7.2 and windows 11

**Comment by lewis6991** [comment]
Please read the README. This plugin requires Neovim nightly.
