### ISSUE TITLE
scrollbar is included in diff when using neovim's `-d` flag

### ISSUE THREAD

**Issue by 0xAdk** [lewis6991/satellite.nvim#21]
**Describe the bug**
When opening neovim with the `-d` flag (assuming the file is large enough to have the scroll bar) it will attempt to include the scrollbar in the diff

**To Reproduce**
find / make a file that has more lines then your window size
open the file using neovim's `-d` flag
observe the file seemingly being diffed against nothing
run `:SatelliteDisable` and it goes away

**Expected behavior**
the scroll bar isn't included in the diff

**Screenshots**
![image](https://user-images.githubusercontent.com/29005635/187376989-be4ca48d-8d90-4798-94ee-6d9a153d07ec.png)

**Comment by kmac** [comment]
Holy smokes, I was banging my head against the wall trying to track this issue down.  I was wondering why my nvim -d was seemingly broken on one machine and not another.  It turns out that it was only broken on the machine with the smaller line length, where the scrollbar kicked in.

**Comment by 0xAdk** [comment]
fixed with https://github.com/neovim/neovim/commit/be3d30cacec141bdab6d4bfb94a6fd184479de3b

**Comment by lewis6991** [comment]
Awesome. Thanks a lot!
