### ISSUE TITLE
satellite will remap `m` and cause some delay

### ISSUE THREAD

**Issue by NEX-S** [lewis6991/satellite.nvim#26]
https://github.com/lewis6991/satellite.nvim/blob/609623c88ef9a1e6869dd20443a2027c10502b92/lua/satellite/autocmd/mark.lua#L22

if we map `m` to another keymap, the satellite will remap m and cause some delay.
```lua
vim.keymap.set('n', 'm', '%', { noremap = true, silent = true })
```

**Comment by lewis6991** [comment]
Yes, and?

Please read the README. This is an experimental plugin and the APIs needed in order to implement this plugin robustly do not yet exist.
