### ISSUE TITLE
Bug: notification spam in uncommited files with gitsign enabled

### ISSUE THREAD

**Issue by chrisgrieser** [lewis6991/satellite.nvim#36]
**Describe the bug**
In an untracked file (= whole file has gitsigns in the signcolumn), deleting a larger number of lines results in dozens of notifications that the gitsign row is out of range.

**To Reproduce**
1. create a new file in a git repo
2. have gitsigns enabled for this plugin
3. fill the new file with a few dozen lines
4. delete a larger number of lines at once

**Expected behavior**
no notification spam should happen. Or at the very least having an configuration option to turn off those notifications.

**Screenshots**
<img width="1263" alt="Pasted image 2022-12-27 22 08 44" src="https://user-images.githubusercontent.com/73286100/209722511-f890be14-b3b3-4c65-8505-b8363f814358.png">
<img width="1679" alt="Pasted image 2022-12-27 22 07 08" src="https://user-images.githubusercontent.com/73286100/209722525-68eabb9d-0e04-465c-af47-6638602185a5.png">

**Comment by chrisgrieser** [comment]
okay, since the latest updates those are fixed, but instead deleting a lot of lines results in a bunch of these messages:
```txt
 error(satellite.nvim): handler=gitsigns buf=125 row=30 
 opts={ id = 31, priority = 20, sign_hl_group = "GitSig 
 gnsChange", sign_text = " │" }, err="line value outsi 
 ide range" 
```

**Comment by lewis6991** [comment]
This should be fixed now. Please let me know if not.
