### ISSUE TITLE
the scrollbar of the buffer shifts to the middle of the window when you open NvimTree

### ISSUE THREAD

**Issue by Rishabh672003** [lewis6991/satellite.nvim#37]
**To Reproduce**
1. open nvim-tree with this plugin

**Expected behavior**
the scrollbar should stay there 

**Screenshots**
![image](https://user-images.githubusercontent.com/53911515/210252350-67803273-c3cb-44e5-bfb0-cb55834a14b0.png)
you can see the scrollbar in the middle of the window

**Comment by lewis6991** [comment]
Can not reproduce. Let me know if this is still an issue.
