### ISSUE TITLE
Memory leak on scroll

### ISSUE THREAD

**Issue by nenikitov** [lewis6991/satellite.nvim#40]
**Describe the bug**
- When scrolling files (especially fast scrolling with mouse wheel), Neovim's memory usage increases.
- Eventually causes stutters and even freezes desktop.

**To Reproduce**
1. Load a file large enough to be scrolled
2. Note the memory usage
3. Start scrolling
    - Easy to reproduce when scrolling up and down with mouse wheel
    - Also applies when scrolling with `j` and `k`, but will be slower
4. Note that the memory and CPU usage quickly increase
5. Stop scrolling
6. Notice that memory usage didn't go down

**Expected behavior**
- Scrolling doesn't increase memory usage by much
- After scrolling, memory usage comes back to how it was before scrolling

**Screenshots**
*Note* tested with a file with 64 lines. Scrolled up and down with mouse wheel. Note the `MemB` of the 2nd process.

- Without `satellite.nvim`
    - No scroll
        ![image](https://user-images.githubusercontent.com/44075969/228966082-7c6eea89-3d66-4492-a2c2-3cc7076ac1a3.png)
    - Scrolled a bit
        ![image](https://user-images.githubusercontent.com/44075969/228966193-31db59fb-f49a-4c91-8ea2-b2ceae392737.png)
    - Scrolled some more
        ![image](https://user-images.githubusercontent.com/44075969/228966273-d154bea2-9485-4bec-b8ef-aaad5d3b6b39.png)
- With `satellite.nvim`
    - No scroll
        ![image](https://user-images.githubusercontent.com/44075969/228966463-82d141ed-f6c9-40c8-9b19-6ee3fea5de79.png)
    - Scrolled a bit
        ![image](https://user-images.githubusercontent.com/44075969/228966605-374780ed-e9b5-4826-b6f0-4f57269a78ba.png)
    - Scrolled some more
        ![image](https://user-images.githubusercontent.com/44075969/228966796-27029ec0-ab10-4033-8548-e5427f5cd035.png)

**Additional context**
- Tested with no other plugins enabled
- Tested with both [`packer.nvim`](https://github.com/wbthomason/packer.nvim) and [`lazy.nvim`](https://github.com/folke/lazy.nvim)
- My configuration
    ```lua
    return {
        'lewis6991/satellite.nvim',
        config = function()
            require('satellite').setup()
        end
    }
    ```
- Output of `nvim --version`
    ```
    NVIM v0.9.0-dev-873+g4b9bb3a184
    Build type: RelWithDebInfo
    LuaJIT 2.1.0-beta3
    Compilation: /usr/bin/cc -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=always -fstack-protector-strong -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -DNVIM_UNIBI_HAS_VAR_FROM -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/nenikitov/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/nenikitov/.cache/yay/neovim-git/src/build/include -I/home/nenikitov/.cache/yay/neovim-git/src/build/cmake.config -I/home/nenikitov/.cache/yay/neovim-git/src/neovim/src -I/usr/include -I/usr/include -I/usr/include
    Compiled by nenikitov

    Features: +acl +tui
    See ":help feature-compile"

       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/usr/share/nvim"

    Run :checkhealth for more info
    ```

**Comment by lewis6991** [comment]
Can you figure out which handler is causing the leak?

**Comment by nenikitov** [comment]
Memory leak is still present after removing all handlers
```lua
return {
    "lewis6991/satellite.nvim",
    config = function()
        require("satellite").setup {
            handlers = {
                search = { enable = false },
                diagnostic = { enable = false },
                gitsigns = { enable = false },
                marks = { enable = false }
            }
        }
    end,
}
```

Before scrolling:
![image](https://user-images.githubusercontent.com/44075969/228985647-30b48144-c937-4916-b55b-b716ffe45cf6.png)

After scrolling:
![image](https://user-images.githubusercontent.com/44075969/228985700-efbb0d8c-ad73-45a6-b7c4-0ad2b315a1eb.png)

Forgot to mention, here is the output of `nvim --version` (I also updated the isse)
```
NVIM v0.9.0-dev-873+g4b9bb3a184
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=always -fstack-protector-strong -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -DNVIM_UNIBI_HAS_VAR_FROM -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/nenikitov/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/nenikitov/.cache/yay/neovim-git/src/build/include -I/home/nenikitov/.cache/yay/neovim-git/src/build/cmake.config -I/home/nenikitov/.cache/yay/neovim-git/src/neovim/src -I/usr/include -I/usr/include -I/usr/include
Compiled by nenikitov

Features: +acl +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by lewis6991** [comment]
Thanks for the report. #41 should fix *a* leak. Can you check?

**Comment by nenikitov** [comment]
I don't think it helped with my memory leak:

![image](https://user-images.githubusercontent.com/44075969/229305735-920a68ff-9608-486f-a86e-d22a79cd7acf.png)
![image](https://user-images.githubusercontent.com/44075969/229305698-bbfd0bfa-a937-4b1e-b6e0-4bf849ca9a9e.png)

If it helps, running `:SatelliteDisable` and `:SatelliteEnable` resets the memory usage

**Comment by lewis6991** [comment]
That's not the right commit. It needs to be 385e67fc9942b6ed87086c700c627b581ed583d4

**Comment by nenikitov** [comment]
Hello,

I didn't notice that the fix is on a separate branch. After updating to the right commit:
![image](https://user-images.githubusercontent.com/44075969/229367252-e1859a99-c5f0-4ae7-8105-f530c70cd9c3.png)

It seems like the memory leak is fixed (here is the memory usage after scrolling):
![image](https://user-images.githubusercontent.com/44075969/229367300-25e907f4-8521-4907-a058-8674a62e5c49.png)

Thank you for the fix
