### ISSUE TITLE
Configurable CURSOR_SYMBOLS

### ISSUE THREAD

**Issue by topaxi** [lewis6991/satellite.nvim#47]
**Is your feature request related to a problem? Please describe.**
I'm getting a `[?]` symbol in the satellitebar, I'm using Fira Code NerdFont. As far as I can see, the symbols in the `CURSOR_SYMBOLS` table are static.

**Describe the solution you'd like**
Making the table configurable would be great, or maybe there's more commonly available glyphs that could be used.

**Comment by lewis6991** [comment]
Ah I see. I changed the symbols to some unicode characters today. I thought this would be ok since most handlers use weird symbols.

**Comment by topaxi** [comment]
I fixed the problem in my case by snooping in your dotfiles. I'm using wezterm and defined Monaco as a [fallback font](https://wezfurlong.org/wezterm/config/fonts.html#fallback). :)
