### ISSUE TITLE
satellite crashes and makes complete neovim unusable

### ISSUE THREAD

**Issue by snaeil** [lewis6991/satellite.nvim#48]
**Describe the bug**
After opening a lua file with `neovim myluafile.lu`, satellite indicates me a problem with `marks.lua` line 28.
With every key stroke, errors appear and make neovim unusable.

I hope that I am not suspecting satellite wrongly but the output is

```
Failed to run `config` for satellite.nvim
...l/share/nvim/lazy/satellite.nvim/lua/satellite/async.lua:50: The coroutine failed with this message: ...vim/lazy/satellite.nvim/lua/satellite/handlers/marks.lua:28: attempt to call field 'list_contains' (a nil value)
stack traceback:
^I...vim/lazy/satellite.nvim/lua/satellite/handlers/marks.lua: in function 'mark_is_builtin'
^I...vim/lazy/satellite.nvim/lua/satellite/handlers/marks.lua:57: in function 'add_mark_to_bar'
^I...vim/lazy/satellite.nvim/lua/satellite/handlers/marks.lua:79: in function 'update'
^I...al/share/nvim/lazy/satellite.nvim/lua/satellite/view.lua:99: in function 'render_handler'
^I...al/share/nvim/lazy/satellite.nvim/lua/satellite/view.lua:170: in function <...al/share/nvim/lazy/satellite.nvim/lua/satellite/view.lua:164>
# stacktrace:
  - /satellite.nvim/lua/satellite/async.lua:50 _in_ **step**
  - /satellite.nvim/lua/satellite/async.lua:71 _in_ **execute**
  - /satellite.nvim/lua/satellite/async.lua:102 _in_ **render**
  - /satellite.nvim/lua/satellite/view.lua:263 _in_ **show_scrollbar**
  - /satellite.nvim/lua/satellite/view.lua:344 _in_ **refresh_bars**
  - /satellite.nvim/lua/satellite/view.lua:371 _in_ **enable**
  - /satellite.nvim/lua/satellite.lua:11 _in_ **enable**
  - /satellite.nvim/lua/satellite.lua:173 _in_ **setup**
```

**To Reproduce**
1. Open lua file with `neovim myluafile.lua`
2. Instantly see error messages which appear with every key stroke

**Expected behavior**
No errors

**Screenshots**
![2023-07-05-192450_1913x1032_scrot](https://github.com/lewis6991/satellite.nvim/assets/52743746/c1d90498-c6ec-48f4-a399-65be74cd561f)

**Additional context**
If I am not wrong, this doesn't happen for older commits.

**Comment by lewis6991** [comment]
What's your neovim version? Nightly is currently required.

**Comment by snaeil** [comment]
I was using `0.9.1`. Switching to nightly did it for me.
Thank you for the fast reply! :-)

**Comment by Pheon-Dev** [comment]
Me too!! I had to set `marks.show_builtins` to `false` for it to work. I'm using `v0.9.1' too but still getting the same errors.

**Comment by lewis6991** [comment]
You need to use nightly. v0.9.1 is not supported.
