### ISSUE TITLE
Wrong version check?

### ISSUE THREAD

**Issue by 867380699** [lewis6991/satellite.nvim#50]
**Describe the bug**
As far as i know, the current stable release version is `0.9`.

**To Reproduce**
1. Just open `neovim`

**Expected behavior**
plugin works

**Screenshots**

```
Error detected while processing /home/home/.config/nvim/init.lua:                               
satellite.nvim only supports nvim 0.10 and newer                                              
Press ENTER or type command to continue    
```

**Comment by lewis6991** [comment]
Satellite.nvim require neovim nightly.
