### ISSUE TITLE
Width setting

### ISSUE THREAD

**Issue by Jendker** [lewis6991/satellite.nvim#55]
I am trying to change the width of the scrollbar. Changing `width` in the config doesn't change it. Is there a proper way to approach it?

**Comment by lewis6991** [comment]
No. The width of the scrollbar itself not configurable.

**Comment by Jendker** [comment]
I see. What is the function of width currently? I would like to add respective entry to help.

**Comment by lewis6991** [comment]
It sets the width of the floating window used to display the scrollbar as some decorations (like Gitsigns) are next to the bar.

The setting should probably be removed.

**Comment by lewis6991** [comment]
Just double-checked. That setting isn't used at all so can be removed from the readme.
