### ISSUE TITLE
Make scrollbar background transparent

### ISSUE THREAD

**Issue by franroa** [lewis6991/satellite.nvim#60]
**Problem**
I have made my neovim config transparent, except the scrollbar. I dont know how to do it

**Possible Solution**
An option to change opacity, or a highlight group to configure the background

**Additional Context:**

<img width="170" alt="scroll" src="https://github.com/lewis6991/satellite.nvim/assets/2432583/9a8242a6-71e0-44d6-8d31-4e68d4ccca2d">

**Comment by adkevin3307** [comment]
I'm having the same issue. I think this is caused by `winblend` (https://github.com/neovim/neovim/issues/18576).
Currently, you can set `winblend` to 0 to make scrollbar background transparent.
