### ISSUE TITLE
Scrollbar Disappears in Large File

### ISSUE THREAD

**Issue by Isrothy** [lewis6991/satellite.nvim#65]
**Describe the bug**

**To Reproduce**
1. Open a very large file.

**Expected behavior**
There should be a scrollbar on the right side.

**Screenshots**
<img width="1440" alt="image" src="https://github.com/lewis6991/satellite.nvim/assets/61075605/25521fcf-cd8d-4859-80ad-675cbd62d955">

I guess this is because `height_to_virtual` function that rounds down the height of scrollbar, which is therefore set to 0.

**Comment by lewis6991** [comment]
> Open a very large file.

How large?

Please make sure to provide more precise instructions when you raise issues on projects.

**Comment by Isrothy** [comment]
It's 78425 lines in my case.
