### ISSUE TITLE
Different signs for different types of diagnostics

### ISSUE THREAD

**Issue by ADIX7** [lewis6991/satellite.nvim#79]
Add support for different signs for diagnostics based on the type.

Currently in the config for diagnostics there is only a `signs` property. Instead of this it could be a table like this:
```
signs: {
    error: { '-', '=', '≡' },
    warning: { '-', '=', '≡' },
    info: { '-', '=', '≡' },
    hint: { '-', '=', '≡' },
}
```

This config would give the same look as it is currently, but one could use
```
signs: {
    error: {'E' },
    warning: { 'W' },
    info: { 'I' },
    hint: { 'H' },
}
```
to differentiate what type of diagnostic is that. I know currently it is possible to differentiate with highlight groups, but different signs would be more natural (at least for me, but this is an extra option, so the current behaviour can be kept if someone likes that as well)

**Comment by ADIX7** [comment]
Would you accept a PR for this?

**Comment by lewis6991** [comment]
sure

**Comment by ADIX7** [comment]
Here is the PR for this #80
