### ISSUE TITLE
feature request: partial cell scrollbar

### ISSUE THREAD

**Issue by budswa** [lewis6991/satellite.nvim#8]
At the moment the scrollbar renders as whole cells, I believe this is done because it highlights the whole cell. If you used characters like ▁▂▃▄▆▇█ for the top and bottom of the scrollbar you could have a much more precise position and it will appear to scroll smoother on larger files. Using those same characters, you can invert the highlights and make them appear as they are incrementing from the top. 

x

**Comment by lewis6991** [comment]
This is something I've explicitly not implemented. The main focus of satellite.nvim is to provide signs like `signcolumn` but for the entire buffer.

One of the features required for this to work is that highlights in Neovim can be blended. So in order for signs to appear on top of the scrollbar (which is important), the scrollbar must be implemented with whitespace characters.
