### ISSUE TITLE
Cursor line and number flicking

### ISSUE THREAD

**Issue by vunhatchuong** [lewis6991/satellite.nvim#81]
**Describe the bug**
The plugin makes the cursor line and number flicker when going up and down.

https://github.com/user-attachments/assets/fadfd6eb-4117-41bb-9e3f-7a313ad606bf

**To Reproduce**

1. Config:

```lua
{
    "lewis6991/satellite.nvim",
    lazy = false,
    opts = {
        current_only = true,
        handlers = {
            cursor = { enable = false },
            gitsigns = { enable = false },
            diagnostic = { enable = false },
            marks = { enable = false },
            quickfix = { enable = false },
        },
    }}
```

2. Open a file and start going up and down.

**Additional context**

I tested `petertriho/nvim-scrollbar` and it doesn't have this problem.

**Comment by lewis6991** [comment]
Hmm not sure.
